# -*- coding: utf-8 -*-
"""DataConcat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gMF23erfec8KzatJGqiGVS9aJLKPyqLs

Pengumpulan DataFrame
"""

import pandas as pd

data1 = pd.read_csv('Recon OS Scan.csv')

data1

data2 = pd.read_csv('Recon Port Scan.csv')

data2

dtRevisi = data2.iloc[:159025, :]

dtRevisi

data3 = pd.read_csv('Recon Vulnerability Scan.csv')

data3

"""Penggabungan DataFrame"""

DataJoin = pd.concat([data1, dtRevisi, data3], ignore_index=True)

DataJoin.columns.values

DataJoin

"""Pemisahan X dan Y"""

x = DataJoin.iloc[:, 7:76]

x

y = DataJoin.iloc[:, 83:84]

y

"""Melatih Data serta Evaluasi"""

from sklearn.model_selection import train_test_split

x = x.fillna(method='ffill')
y = y.fillna(method='ffill')

x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.3, random_state = 42)

from sklearn import tree
from sklearn.tree import DecisionTreeClassifier

uji = DecisionTreeClassifier(criterion='entropy', splitter = 'random')
uji.fit(x_train,y_train)

y_pred = uji.predict(x_test)

y_pred

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)

accuracy

"""Mem-Visualisasikan dengan metode DecisionTree"""

import matplotlib.pyplot as plt
import numpy as np

fig = plt.figure(figsize = (10, 7))
tree.plot_tree(uji, feature_names = x.columns.values, class_names = np.array([ 'Recon OS Scan','Recon Port Scan','Recon Vulnerability Scan']), filled = True)
plt.show()

import seaborn as sea
from sklearn import metrics
label = np.array([ 'Recon OS Scan','Recon Port Scan','Recon Vulnerability Scan'])

import matplotlib.pyplot as plt
conf_matrix = metrics.confusion_matrix(y_test, y_pred)
plt.figure(figsize=(10, 10))
sea.heatmap(conf_matrix, annot=True, xticklabels=label, yticklabels=label)
plt.xlabel('Prediksi')
plt.ylabel('Fakta')
plt.show()